# Generated by Django 4.0.6 on 2022-07-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobileNo',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
