# Generated by Django 4.0.6 on 2022-07-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='failedLoginCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastFailedLoginTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
