# Generated by Django 4.0.6 on 2022-07-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customuser_failedlogincount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
