# Generated by Django 4.0.6 on 2022-07-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='failedLoginCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
