# Generated by Django 4.0.6 on 2022-07-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customuser_failedlogincount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unlockTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
