# Generated by Django 4.0.6 on 2022-07-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customuser_unlocktime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='unlockTime',
        ),
    ]
