# Generated by Django 4.0.6 on 2022-07-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_customuser_unlocktime'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unlockTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
