# Generated by Django 4.0.6 on 2022-07-13 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_customuser_unlocktime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='unlockTime',
        ),
    ]
